name: fighting-game-watcher-GGST
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - argh=0.26.2
  - astroid=2.7.3
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=21.2.0
  - autopep8=1.5.6
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.0
  - black=21.9b0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - click=8.0.1
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cryptography=3.4.7
  - dataclasses=0.8
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - docutils=0.17.1
  - entrypoints=0.3
  - flake8=3.8.4
  - flask=2.0.1
  - freeglut=3.2.1
  - freetype=2.10.4
  - future=0.18.2
  - git=2.23.0
  - helpdev=0.7.1
  - icu=68.1
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - intel-openmp=2021.3.0
  - intervaltree=3.0.2
  - ipykernel=6.4.1
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - itsdangerous=2.0.1
  - jasper=2.0.14
  - jbig=2.1
  - jedi=0.17.2
  - jinja2=3.0.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=7.0.2
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - keyring=23.2.1
  - lazy-object-proxy=1.6.0
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libdeflate=1.7
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopencv=4.5.3
  - libpng=1.6.37
  - libprotobuf=3.16.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.3.0
  - mypy_extensions=0.4.3
  - nbclient=0.5.4
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - numpy=1.21.2
  - numpydoc=1.1.0
  - opencv=4.5.3
  - openssl=1.1.1n
  - packaging=21.0
  - pandas=1.3.3
  - pandoc=2.14.2
  - pandocfilters=1.5.0
  - paramiko=2.7.2
  - parso=0.7.0
  - pathspec=0.9.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - platformdirs=2.3.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py-opencv=4.5.3
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydocstyle=6.1.1
  - pyflakes=2.2.0
  - pygments=2.10.0
  - pylint=2.10.2
  - pyls-black=0.4.6
  - pyls-spyder=0.3.2
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.36.2
  - python_abi=3.9
  - pytz=2021.1
  - pywin32=301
  - pywin32-ctypes=0.2.0
  - pyyaml=5.4.1
  - pyzmq=22.2.1
  - qdarkstyle=2.8.1
  - qt=5.12.9
  - qtawesome=1.0.3
  - qtconsole=5.1.1
  - qtpy=1.11.1
  - regex=2021.8.28
  - requests=2.25.1
  - rope=0.19.0
  - rtree=0.9.7
  - setuptools=58.0.4
  - six=1.16.0
  - snowballstemmer=2.1.0
  - sortedcontainers=2.4.0
  - sphinx=4.2.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.36.0
  - tbb=2021.3.0
  - testpath=0.5.0
  - textdistance=4.2.1
  - three-merge=0.1.1
  - toml=0.10.2
  - tomli=1.2.1
  - tornado=6.1
  - traitlets=5.1.0
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - ucrt=10.0.20348.0
  - ujson=4.1.0
  - urllib3=1.26.6
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - watchdog=1.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.1
  - wheel=0.37.0
  - win_inet_pton=1.1.0
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.5.0

